# # Ruff configuration for Velithon

# [tool.ruff]
# target-version = "py310"
# line-length = 88
# extend-exclude = [
#     "target",
#     "dist", 
#     "build",
#     "*.so",
#     "*.pyd",
# ]

# [tool.ruff.lint]
# select = [
#     "E",   # pycodestyle errors
#     "W",   # pycodestyle warnings
#     "F",   # pyflakes
#     "I",   # isort
#     "B",   # flake8-bugbear
#     "C4",  # flake8-comprehensions
#     "UP",  # pyupgrade
#     "PL",  # pylint
#     "SIM", # flake8-simplify
#     "TID", # flake8-tidy-imports
#     "Q",   # flake8-quotes
#     "FBT", # flake8-boolean-trap
#     "C90", # mccabe
#     "N",   # pep8-naming
# ]

# ignore = [
#     "E501",   # line too long, handled by formatter
#     "B008",   # do not perform function calls in argument defaults
#     "C901",   # too complex
#     "PLR0913", # too many arguments
#     "PLR0915", # too many statements
#     "PLR2004", # magic value used in comparison
#     "FBT001",  # boolean typed positional argument in function definition
#     "FBT002",  # boolean default positional argument in function definition
# ]

# [tool.ruff.lint.per-file-ignores]
# "tests/*" = ["PLR2004", "S101", "TID252"]
# "benchmarks/*" = ["PLR2004", "S101"]

# [tool.ruff.lint.isort]
# known-first-party = ["velithon"]

# [tool.ruff.format]
# quote-style = "double"
# indent-style = "space"
# skip-magic-trailing-comma = false
# line-ending = "auto"
